/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as StoryRouteImport } from './routes/story'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as CustomOrdersRouteImport } from './routes/custom-orders'
import { Route as IndexRouteImport } from './routes/index'

const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomOrdersRoute = CustomOrdersRouteImport.update({
  id: '/custom-orders',
  path: '/custom-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/custom-orders': typeof CustomOrdersRoute
  '/menu': typeof MenuRoute
  '/story': typeof StoryRoute
  '/visit': typeof VisitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/custom-orders': typeof CustomOrdersRoute
  '/menu': typeof MenuRoute
  '/story': typeof StoryRoute
  '/visit': typeof VisitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/custom-orders': typeof CustomOrdersRoute
  '/menu': typeof MenuRoute
  '/story': typeof StoryRoute
  '/visit': typeof VisitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/custom-orders' | '/menu' | '/story' | '/visit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/custom-orders' | '/menu' | '/story' | '/visit'
  id: '__root__' | '/' | '/custom-orders' | '/menu' | '/story' | '/visit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomOrdersRoute: typeof CustomOrdersRoute
  MenuRoute: typeof MenuRoute
  StoryRoute: typeof StoryRoute
  VisitRoute: typeof VisitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-orders': {
      id: '/custom-orders'
      path: '/custom-orders'
      fullPath: '/custom-orders'
      preLoaderRoute: typeof CustomOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomOrdersRoute: CustomOrdersRoute,
  MenuRoute: MenuRoute,
  StoryRoute: StoryRoute,
  VisitRoute: VisitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
